main: net.karanteeni.teleportal.Teleportal
name: Teleportal
version: 1.0
author: Nuubles
description: Manages teleportation extensions such as portals and warps 
api-version: 1.13
depend: [KaranteeniCore]

permissions:
  #all permissions
  teleportal.warp.edit.create:
    description: create a new warp
  teleportal.warp.edit.rename:
    description: rename an existing warp
  teleportal.warp.edit.move:
    description: move warp to another location
  teleportal.warp.edit.delete:
    description: deletes an existing warp
  teleportal.warp.edit.permission:
    description: set permission to use warp
  teleportal.warp.use:
    description: teleport to a warp
  teleportal.warp.send:
    description: teleport another player to this warp