package net.karanteeni.core.database;

public enum QueryState {
	INSERTION_SUCCESSFUL,
	INSERTION_SUCCESSFUL_UPDATED,
	UPDATE_SUCCESSFUL,
	REMOVAL_SUCCESSFUL,
	TABLE_CREATION_SUCCESSFUL,
	TABLE_CREATION_FAIL,
	ERROR_NO_CONNECTION,
	INSERTION_FAIL_ALREADY_EXISTS,
	INSERTION_FAIL_OTHER,
	UPDATE_FAIL,
	REMOVAL_FAIL_NO_DATA,
	REMOVAL_FAIL_OTHER,
	INSERTION_FAIL_NO_KEY,	
	UPDATE_FAIL_NO_KEY
}
