main: net.karanteeni.wgef.WGEF
name: WGExtraFlags
version: 1.0
author: Nuubles
description: provides extra flags to worldguard
api-version: 1.15
depend: [KaranteeniCore, WorldGuard]
softdepend: [NoteBlockAPI]