main: net.karanteeni.currency.KCurrency
name: KCurrency
version: 1.0
author: Nuubles
description: The plugin which handles all money related tasks
api-version: 1.13
depend: [KaranteeniCore]

permissions:
  #all permissions
  kcurrency.baltop:
    description: check the baltop
  kcurrency.pay: 
    description: pay another player with X amount of money
  kcurrency.bal.own: 
    description: check your own balance
  kcurrency.bal.other: 
    description: check someone elses balance
  kcurrency.eco.take: 
    description: take money away from player
  kcurrency.eco.give: 
    description: give money to player
  #wildcards
  kcurrency.bal.*:
    children:
      kcurrency.bal.own: true
      kcurrency.bal.other: true
  kcurrency.eco.*:
    children:
      kcurrency.eco.take: true     
      kcurrency.eco.give: true
  kcurrency.*:
    children:
      kcurrency.bal.*: true
      kcurrency.eco.*: true
      kcurrency.baltop: true
      kcurrency.pay: true