main: net.karanteeni.groups.KaranteeniPerms
name: KaranteeniPerms
version: 1.0
author: Nuubles
description: This plugin handles all BASIC permissions and groups in worlds
api-version: 1.13
depend: [KaranteeniCore]