main: net.karanteeni.chatar.Chatar
name: Chatar
version: 1.0
author: Nuubles
description: Manages messaging and chat in the game
api-version: 1.16
depend: [KaranteeniCore]
softdepend: [KaranteeniPerms]
database: true

permissions:
  chatar.message.use:
    description: gives access to the /message command
  chatar.message.color:
    description: use colors in /message
  chatar.message.format:
    description: use formatting in /message
  chatar.message.magic:
    description: use random text in /message
  chatar.message.rgb:
    description: use rgb text in /message
  chatar.reply:
    description: gives access reply instantly to a message using /reply
  chatar.chat.color:
    description: use colors in chat
  chatar.chat.format:
    description: use formatting in chat
  chatar.chat.magic:
    description: use random text in chat
  chatar.chat.rgb:
    description: use rgb text in chat
  chatar.chat.tag:
    description: allows the user to tag other players
    
  chatar.socialspy:
    description: listen to other peoples messages
  chatar.party.create:
    description: create a chat party
  chatar.party.info:
    description: view party info
  
  chatar.broadcast:
    description: broadcast a message to the whole bungeecord network
  
  chatar.ignore.use:
    description: ignore other players
  chatar.ignore.immune:
    description: players with this permission cannot be ignored